import{S as p,i as d}from"./assets/vendor-B07T6_gy.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const h="48307401-677547b5d41e0bab8fbb923eb",g="https://pixabay.com/api/";function y(o,n=1){const e=`${g}?key=${h}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}`;return fetch(e).then(s=>{if(!s.ok)throw new Error("Failed to fetch images");return s.json()})}const L=document.getElementById("search-form"),u=document.querySelector(".gallery"),i=document.getElementById("load-more"),f=document.getElementById("loader"),b=new p(".gallery a",{captionsData:"alt",captionDelay:250});let a="",l=1;L.addEventListener("submit",function(o){if(o.preventDefault(),a=o.target.elements.query.value.trim(),!a){d.error({title:"Error",message:"Please enter a search query!"});return}u.innerHTML="",l=1,m(a,l)});i.addEventListener("click",function(){l+=1,m(a,l)});function m(o,n){f.classList.remove("hidden"),y(o,n).then(e=>{e.hits.length===0?(d.warning({title:"No Results",message:"No images found. Try another search!"}),i.classList.add("hidden")):(w(e.hits),i.classList.remove("hidden"),e.hits.length<20&&i.classList.add("hidden"))}).catch(e=>{d.error({title:"Error",message:"Something went wrong. Please try again later."})}).finally(()=>{f.classList.add("hidden")})}function w(o){const n=o.map(e=>`
    <a href="${e.largeImageURL}" class="gallery__item">
      <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      <div class="info">
        <p>❤️ Likes: ${e.likes}</p>
        <p>👁 Views: ${e.views}</p>
        <p>💬 Comments: ${e.comments}</p>
        <p>⬇ Downloads: ${e.downloads}</p>
      </div>
    </a>
  `).join("");u.insertAdjacentHTML("beforeend",n),b.refresh()}window.global||(window.global=window);
//# sourceMappingURL=index.js.map
